### ISSUE TITLE
Inconsistent behaviour when searching for non-existent locations

### ISSUE THREAD

**Issue by Jintzo** [devfacet/weather#5]
When searching for weather information for non-existent locations, XML parsing errors occur (see [this runkit](https://runkit.com/58c66d46a26493001430359c/58c66d46a26493001430359d))
![bla](https://cloud.githubusercontent.com/assets/5368029/23849565/5bb1f9b8-07dc-11e7-9ec7-01b32a364b2f.png)

**Comment by devfacet** [comment]
Fixed by 6176ab06202bbeaad3dffdb9960eefee708a32be

`npm install weather-js@2`
